### ISSUE TITLE
Invalid Minecraft Dungeons key

### ISSUE THREAD

**Issue by MatthieuLepers** [FModel/Unreal-Game-Keys#2]
Hello, the key for minecraft dungeon not work anymore, can you update it ?

**Comment by GMatrixGames** [comment]
Hello, is this the correct AES key? If so, please reply stating such and I will update the file

0xCCB6409075433E2BE4CC249C48D9B5350741A9F9399A51B9E3B6742EF13947FD

**Comment by MatthieuLepers** [comment]
Hi ! This one work for game v1.12.0.0 : 0x72FA28089D1E511139E4EA804A6577B37070940DC43D72D62D2C889A728D9620 found on official modding discord

**Comment by Delfite** [comment]
For those of you looking for the latest AES Decryption keys for MCD and stumbled onto this issues page looking for such, the DokuCraft Discord has the latest keys under the "Pinned Messages" section in the #dungeons text channel. The key used in the current latest version of the game (that being 1.16.3.0 as of writing) is: 0xAE74A59361EFFB891D252EB410E13ED985D1941010F664A7570A774B2C9D0D6F

Please visit the discord as I won't be posting this info anywhere else: https://discord.gg/NrqHSXNFcp
