### ISSUE TITLE
Invalid key for MC dungeons

### ISSUE THREAD

**Issue by LuckyPants12** [FModel/Unreal-Game-Keys#3]
It seems that with the new update the key may have changed, is someone can check that would be amazing!
tysm

**Comment by MatthieuLepers** [comment]
Hi, here is the key for v1.15.1.0 : 0xE06CE229E7A7051CED9969D49740A5C5C6A8C8F2F1B04186E589BE01D026140E

**Comment by LuckyPants12** [comment]
Yeah i got it alredy, thanks tho, there is a discord server where the key is released almost as soon as the update arrives
