### ISSUE TITLE
Add new key

### ISSUE THREAD

**Issue by lynrayy** [FModel/Unreal-Game-Keys#4]
EntropyCentre-Win64-Shipping
0x72463A7B70FA819E286295CF74C280AC7C928D0BCB349CF811CAF1AE27780A41

**Comment by lynrayy** [comment]
Where are all the keys?

**Comment by GMatrixGames** [comment]
Please refer to the updated README

**Comment by lynrayy** [comment]
I can't find keys on the cs rin website. It is too confusing and half of spoilers are hidden. Shitty website IMO

**Comment by lynrayy** [comment]
![image](https://github.com/FModel/Unreal-Game-Keys/assets/59417884/4865ce2e-4997-45b9-b49d-f8a4dab46f70)

**Comment by GMatrixGames** [comment]
Any keys that are valid are under the "Keys" spoiler. The reason they are in spoilers is so they are collapsible and not take up too much space.

![image](https://github.com/FModel/Unreal-Game-Keys/assets/25112532/73992242-2a0d-4036-b8ac-5614b1ca83cd)
